import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/header';
export const metadata: Metadata = {
  title: 'Royals',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='bg-background font-sans antialiased'>
        <Header />
        {children}
      </body>
    </html>
  );
}
