import type { Metadata } from 'next';
import './globals.css';
import AuthProvider from '@/components/sesson-provider';
import ReactQueryProvider from '@/components/query-provider';
export const metadata: Metadata = {
  title: 'Royals',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='bg-background font-sans antialiased'>
        <AuthProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
